-- begin SRVCAT_SERVICE
alter table SRVCAT_SERVICE add constraint FK_SRVCAT_SERVICE_ON_OWNER foreign key (OWNER_ID) references SEC_USER(ID)^
create index IDX_SRVCAT_SERVICE_ON_OWNER on SRVCAT_SERVICE (OWNER_ID)^
-- end SRVCAT_SERVICE
-- begin SRVCAT_AGREEMENT_PARAMS
alter table SRVCAT_AGREEMENT_PARAMS add constraint FK_SRVCAT_AGREEMENT_PARAMS_ON_TYPE_AGREEMENT foreign key (TYPE_AGREEMENT_ID) references SRVCAT_TYPE_AGREEMENT(ID)^
create index IDX_SRVCAT_AGREEMENT_PARAMS_ON_TYPE_AGREEMENT on SRVCAT_AGREEMENT_PARAMS (TYPE_AGREEMENT_ID)^
-- end SRVCAT_AGREEMENT_PARAMS
-- begin SRVCAT_AGREEMENT_CONFIRM
alter table SRVCAT_AGREEMENT_CONFIRM add constraint FK_SRVCAT_AGREEMENT_CONFIRM_ON_TYPE_AGREEMENT foreign key (TYPE_AGREEMENT_ID) references SRVCAT_TYPE_AGREEMENT(ID)^
alter table SRVCAT_AGREEMENT_CONFIRM add constraint FK_SRVCAT_AGREEMENT_CONFIRM_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SRVCAT_AGREEMENT_CONFIRM add constraint FK_SRVCAT_AGREEMENT_CONFIRM_ON_SERVICE foreign key (SERVICE_ID) references SRVCAT_SERVICE(ID)^
create index IDX_SRVCAT_AGREEMENT_CONFIRM_ON_TYPE_AGREEMENT on SRVCAT_AGREEMENT_CONFIRM (TYPE_AGREEMENT_ID)^
create index IDX_SRVCAT_AGREEMENT_CONFIRM_ON_USER on SRVCAT_AGREEMENT_CONFIRM (USER_ID)^
create index IDX_SRVCAT_AGREEMENT_CONFIRM_ON_SERVICE on SRVCAT_AGREEMENT_CONFIRM (SERVICE_ID)^
-- end SRVCAT_AGREEMENT_CONFIRM
-- begin SRVCAT_AGREEMENT_REQUEST
alter table SRVCAT_AGREEMENT_REQUEST add constraint FK_SRVCAT_AGREEMENT_REQUEST_ON_TYPE_AGREEMENT foreign key (TYPE_AGREEMENT_ID) references SRVCAT_TYPE_AGREEMENT(ID)^
alter table SRVCAT_AGREEMENT_REQUEST add constraint FK_SRVCAT_AGREEMENT_REQUEST_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table SRVCAT_AGREEMENT_REQUEST add constraint FK_SRVCAT_AGREEMENT_REQUEST_ON_SERVICE foreign key (SERVICE_ID) references SRVCAT_SERVICE(ID)^
create index IDX_SRVCAT_AGREEMENT_REQUEST_ON_TYPE_AGREEMENT on SRVCAT_AGREEMENT_REQUEST (TYPE_AGREEMENT_ID)^
create index IDX_SRVCAT_AGREEMENT_REQUEST_ON_USER on SRVCAT_AGREEMENT_REQUEST (USER_ID)^
create index IDX_SRVCAT_AGREEMENT_REQUEST_ON_SERVICE on SRVCAT_AGREEMENT_REQUEST (SERVICE_ID)^
-- end SRVCAT_AGREEMENT_REQUEST
-- begin SRVCAT_TYPE_AGREEMENT
alter table SRVCAT_TYPE_AGREEMENT add constraint FK_SRVCAT_TYPE_AGREEMENT_ON_SERVICE foreign key (SERVICE_ID) references SRVCAT_SERVICE(ID)^
create index IDX_SRVCAT_TYPE_AGREEMENT_ON_SERVICE on SRVCAT_TYPE_AGREEMENT (SERVICE_ID)^
-- end SRVCAT_TYPE_AGREEMENT
-- begin SRVCAT_SERVICE_TEAM
alter table SRVCAT_SERVICE_TEAM add constraint FK_SRVCAT_SERVICE_TEAM_ON_PARTICIPANT foreign key (PARTICIPANT_ID) references SEC_USER(ID)^
alter table SRVCAT_SERVICE_TEAM add constraint FK_SRVCAT_SERVICE_TEAM_ON_SERVICE foreign key (SERVICE_ID) references SRVCAT_SERVICE(ID)^
create index IDX_SRVCAT_SERVICE_TEAM_ON_PARTICIPANT on SRVCAT_SERVICE_TEAM (PARTICIPANT_ID)^
create index IDX_SRVCAT_SERVICE_TEAM_ON_SERVICE on SRVCAT_SERVICE_TEAM (SERVICE_ID)^
-- end SRVCAT_SERVICE_TEAM
